'use strict';
// The 28 rooms. Order is pipeline order; file names match room modules.
module.exports = [
  { num: 1,  id: 'intake',      title: 'Intake Desk',            phase: 'Intake' },
  { num: 2,  id: 'conflicts',   title: 'Ethics & Conflicts',     phase: 'Intake' },
  { num: 3,  id: 'retainer',    title: 'Retainer',               phase: 'Intake' },
  { num: 4,  id: 'value',       title: 'Case Value',             phase: 'Intake' },
  { num: 5,  id: 'client',      title: 'Client Desk',            phase: 'Intake' },
  { num: 6,  id: 'chronology',  title: 'Chronology',             phase: 'Build' },
  { num: 7,  id: 'research',    title: 'Research Desk',          phase: 'Build' },
  { num: 8,  id: 'citations',   title: 'Citation Check',         phase: 'Build' },
  { num: 9,  id: 'jurisdiction',title: 'Jurisdiction Desk',      phase: 'Build' },
  { num: 10, id: 'pleadings',   title: 'Pleadings',              phase: 'Build' },
  { num: 11, id: 'courtbook',   title: 'Court Book',             phase: 'Build' },
  { num: 12, id: 'discovery',   title: 'Discovery Desk',         phase: 'Discover' },
  { num: 13, id: 'review',      title: 'Document Review',        phase: 'Discover' },
  { num: 14, id: 'depositions', title: 'Depositions',            phase: 'Discover' },
  { num: 15, id: 'experts',     title: 'Experts',                phase: 'Discover' },
  { num: 16, id: 'evidence',    title: 'Evidence Room',          phase: 'Discover' },
  { num: 17, id: 'tools',       title: 'Tools ×20',              phase: 'Discover' },
  { num: 18, id: 'briefs',      title: 'Brief Writer',           phase: 'Argue' },
  { num: 19, id: 'moot',        title: 'Moot Room',              phase: 'Argue' },
  { num: 20, id: 'trialbook',   title: 'Trial Book',             phase: 'Argue' },
  { num: 21, id: 'calendar',    title: 'Trial Calendar',         phase: 'Argue' },
  { num: 22, id: 'filing',      title: 'Filing Room',            phase: 'Argue' },
  { num: 23, id: 'adr',         title: 'Mediation & ADR',        phase: 'Resolve' },
  { num: 24, id: 'waterfall',   title: 'Settlement Waterfall',   phase: 'Resolve' },
  { num: 25, id: 'judgment',    title: 'Judgment & Enforcement', phase: 'Resolve' },
  { num: 26, id: 'closing',     title: 'Closing Room',           phase: 'Resolve' },
  { num: 27, id: 'desk',        title: 'Workflow',               phase: 'Always on' },
  { num: 28, id: 'books',       title: 'Trust & Books',          phase: 'Always on' },
];
